[workspace]
members = []
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["Kristofers Solo <dev@kristofers.xyz>"]
edition = "2024"

[workspace.dependencies]
claims = "0.8"
clap = { version = "4.5", features = ["derive"] }
color-eyre = "0.6"
rstest = "0.26"
strum = "0.27"
thiserror = "2"

[workspace.lints.clippy]
nursery = "warn"
pedantic = "warn"
unwrap_used = "warn"
