[workspace]
members = ["bench-common", "bench-runner", "bench-server"]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["Kristofers Solo <dev@kristofers.xyz>"]
edition = "2024"

[workspace.dependencies]
bench-common = { path = "bench-common" }
claims = "0.8"
clap = { version = "4.5", features = ["derive"] }
miette = { version = "7", features = ["fancy"] }
rcgen = "0.14"
rstest = "0.26"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.27", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["full"] }

[workspace.lints.clippy]
nursery = "warn"
pedantic = "warn"
unwrap_used = "warn"
