[package]
name = "bench-runner"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bench-common.workspace = true
clap.workspace = true
miette.workspace = true
tokio.workspace = true

[lints]
workspace = true
