[package]
name = "common"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rcgen.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
tokio.workspace = true

[lints]
workspace = true
